name: "DQLabs Impact Analysis"
description: "Performs Coalesce YML file impact analysis via DQLabs API during PRs and posts the results as a PR comment"
author: "YourOrg"

inputs:
  api_client_id:
    description: "API Client ID to authenticate with DQLabs"
    required: true

  api_client_secret:
    description: "API Client Secret for authentication with DQLabs"
    required: true

  changed_files_list:
    description: "Comma-separated list of changed Coalesce YML files"
    required: true

  github_token:
    description: "GitHub token to comment on the Pull Request"
    required: true

  dqlabs_base_url:
    description: "Base URL of the DQLabs API"
    required: true

  dqlabs_createlink_url:
    description: "URL to create links in DQLabs"
    required: true

  dqlabs_configurable_keys:
    description: "Comma-separated list of keys to include in the impact analysis report. Available keys: direct_column_count, indirect_column_count, direct_asset_count, indirect_asset_count, direct_column_list, indirect_column_list, direct_asset_list, indirect_asset_list, yml_column_changes"
    required: false
    default: ""

outputs:
  impact_markdown:
    description: "Markdown summary of the impact analysis"


runs:
  using: "node16"
  main: "index.js"